language: node_js
node_js:
  - "6"
  - "5"
  - "4"

env:
  matrix:
    - WEBPACK_VERSION=1.13.1
    - WEBPACK_VERSION=2.1.0-beta.20 EXTRACT_TEXT_VERSION=2.0.0-beta.3
matrix:
  fast_finish: true
  allow_failures:
    - env: WEBPACK_VERSION=2.1.0-beta.20 EXTRACT_TEXT_VERSION=2.0.0-beta.3
before_script:
  - npm rm webpack extract-text-webpack-plugin
  - npm install webpack@$WEBPACK_VERSION extract-text-webpack-plugin@$EXTRACT_TEXT_VERSION
cache:
  directories:
  - node_modules
